'use client';

import { getRequestPollingInterval, getRequestListPollingInterval } from '@/utils/polling';
import { useCallback } from 'react';

/**
 * Smart polling hook for individual request queries.
 * Uses refetchInterval callback to dynamically adjust polling based on request status.
 * The Query type from @tanstack/react-query is complex and dynamically generated by tRPC,
 * making explicit typing impractical here.
 */
export function useRequestPolling() {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- tRPC Query type is dynamically generated
    return useCallback((query: { state: { data: any; error: unknown } }) => {
        if (query.state.error) return false;

        const data = query.state.data;
        if (!data) return 5000;

        return getRequestPollingInterval(data.status);
    }, []);
}

/**
 * Smart polling hook for request list (infinite) queries.
 * Adjusts polling frequency based on whether any requests are in processing state.
 */
export function useRequestListPolling() {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- tRPC InfiniteQuery type is dynamically generated
    return useCallback((query: { state: { data: any } }) => {
        return getRequestListPollingInterval(query.state.data);
    }, []);
}
